// ─── QVAC Bridge (IPC) ────────────────────────────────────────────────────────
// Manages the Bare worklet lifecycle and provides typed RPC to qvac inference.
// Singleton — one worklet shared by the whole app.

import { Worklet } from 'react-native-bare-kit';

// Bundled worklet — generated by `npm run bundle:worklet`
let workletSource: string;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  workletSource = require('../../worklet/bundle.js') as string;
} catch {
  workletSource = '// worklet bundle not generated yet — run: npm run bundle:worklet';
}

interface PendingRequest {
  resolve: (value: Record<string, unknown>) => void;
  reject: (err: Error) => void;
  onEvent?: (evt: string, payload: Record<string, unknown>) => void;
}

class QvacBridgeClass {
  private worklet: Worklet | null = null;
  private pending = new Map<string, PendingRequest>();
  private readyPromise: Promise<void>;
  private readyResolve!: () => void;
  private _buffer = '';

  constructor() {
    this.readyPromise = new Promise((res) => {
      this.readyResolve = res;
    });
  }

  start(): void {
    if (this.worklet) return;
    this.worklet = new Worklet();
    // IPC is a streamx Duplex; cast to access stream events and write
    const ipc = this.worklet.IPC as unknown as {
      on: (event: string, cb: (data: Buffer) => void) => void;
      write: (data: Buffer | string) => void;
    };

    ipc.on('data', (data: Buffer) => {
      this._buffer += data.toString();
      const lines = this._buffer.split('\n');
      this._buffer = lines.pop() ?? '';

      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const parsed = JSON.parse(line) as {
            evt: string;
            id: string;
            payload: Record<string, unknown>;
          };
          this._dispatch(parsed.evt, parsed.id, parsed.payload);
        } catch {
          // ignore malformed lines
        }
      }
    });

    this.worklet.start('/worklet.js', workletSource);
  }

  private _dispatch(
    evt: string,
    id: string,
    payload: Record<string, unknown>,
  ): void {
    if (evt === 'ready') {
      this.readyResolve();
      return;
    }

    const req = this.pending.get(id);
    if (!req) return;

    if (evt === 'error') {
      this.pending.delete(id);
      req.reject(new Error((payload.message as string) ?? 'Worklet error'));
      return;
    }

    if (req.onEvent) {
      req.onEvent(evt, payload);
    }

    if (
      evt.endsWith(':done') ||
      evt.endsWith(':result') ||
      evt.endsWith(':cancelled')
    ) {
      this.pending.delete(id);
      req.resolve(payload);
    }
  }

  private async _send(
    cmd: string,
    payload: Record<string, unknown>,
    onEvent?: (evt: string, p: Record<string, unknown>) => void,
  ): Promise<Record<string, unknown>> {
    await this.readyPromise;
    if (!this.worklet) throw new Error('Worklet not started');

    const id = `${cmd}_${Date.now()}_${Math.random().toString(16).slice(2)}`;
    const ipc = this.worklet.IPC as unknown as {
      write: (data: string) => void;
    };

    return new Promise((resolve, reject) => {
      this.pending.set(id, { resolve, reject, onEvent });
      ipc.write(JSON.stringify({ cmd, id, payload }) + '\n');
    });
  }

  // ─── STT ─────────────────────────────────────────────────────────────────────

  async sttLoad(params: {
    modelPath: string;
    vadModelPath?: string;
    cacheDir: string;
    language?: string;
    nThreads?: number;
    vadThreshold?: number;
    vadMinSpeechDurationMs?: number;
    vadMinSilenceDurationMs?: number;
    useGpu?: boolean;
  }): Promise<void> {
    await this._send('stt:load', params as Record<string, unknown>);
  }

  async sttTranscribe(
    pcmFloat32: Float32Array,
    onSegment: (text: string, isFinal: boolean) => void,
  ): Promise<string> {
    const bytes = new Uint8Array(pcmFloat32.buffer, pcmFloat32.byteOffset, pcmFloat32.byteLength);
    const b64 = Buffer.from(bytes).toString('base64');
    const result = await this._send(
      'stt:transcribe',
      { pcm: b64 },
      (evt, p) => {
        if (evt === 'stt:segment' || evt === 'stt:result') {
          onSegment(p.text as string, p.isFinal as boolean);
        }
      },
    );
    return (result.text as string | undefined) ?? '';
  }

  async sttUnload(): Promise<void> {
    await this._send('stt:unload', {});
  }

  // ─── LLM ─────────────────────────────────────────────────────────────────────

  async llmLoad(params: {
    modelPath: string;
    cacheDir: string;
    useGpu?: boolean;
    gpuLayers?: number;
    contextSize?: number;
    temperature?: number;
    topP?: number;
    maxTokens?: number;
  }): Promise<void> {
    await this._send('llm:load', params as Record<string, unknown>);
  }

  async llmGenerate(
    messages: Array<{ role: string; content: string }>,
    onToken: (token: string) => void,
  ): Promise<void> {
    await this._send(
      'llm:generate',
      { messages },
      (evt, p) => {
        if (evt === 'llm:token') {
          onToken(p.token as string);
        }
      },
    );
  }

  async llmCancel(): Promise<void> {
    await this._send('llm:cancel', {});
  }

  async llmUnload(): Promise<void> {
    await this._send('llm:unload', {});
  }

  // ─── TTS ─────────────────────────────────────────────────────────────────────

  async ttsLoad(params: {
    modelDir: string;
    cacheDir: string;
    voiceName?: string;
    speed?: number;
    language?: string;
    numInferenceSteps?: number;
    useGpu?: boolean;
  }): Promise<void> {
    await this._send('tts:load', params as Record<string, unknown>);
  }

  async ttsSpeak(
    text: string,
    sampleRate: number,
    onChunk: (pcm: Float32Array, sampleRate: number) => void,
  ): Promise<void> {
    await this._send(
      'tts:speak',
      { text, sampleRate },
      (evt, p) => {
        if (evt === 'tts:audio') {
          const buf = Buffer.from(p.pcm as string, 'base64');
          const float32 = new Float32Array(
            buf.buffer,
            buf.byteOffset,
            buf.byteLength / 4,
          );
          onChunk(float32, p.sampleRate as number);
        }
      },
    );
  }

  async ttsUnload(): Promise<void> {
    await this._send('tts:unload', {});
  }
}

export const QvacBridge = new QvacBridgeClass();
