apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'expo-module-gradle-plugin'

android {
  namespace "expo.modules.deviceperf"

  defaultConfig {
    minSdkVersion safeExtGet("minSdkVersion", 24)
    targetSdkVersion safeExtGet("targetSdkVersion", 35)
    versionCode 1
    versionName "1.0.0"
  }
}

dependencies {
  implementation project(':expo-modules-core')
}

int safeExtGet(String prop, Integer fallback) {
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
